server:
  port: 8088

spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    password: china666

  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/food-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: Smart$940709